# This is a basic workflow to help you get started with Actions

name: Slack

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  slack:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - name: test
        run: npm run test
      # Runs a single command using the runners shell
      - name: Notify slack
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: "#FF0000"
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: "fail"
          SLACK_TITLE: Message
          SLACK_USERNAME: choyanan
          SLACK_WEBHOOK: ${{ secrets.SLACK_BOT_TOKEN }}
      # Runs a single command using the runners shell
      - name: Notify slack
        if: success()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: "#00FF00"
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: "success"
          SLACK_TITLE: Message
          SLACK_USERNAME: choyanan
          SLACK_WEBHOOK: ${{ secrets.SLACK_BOT_TOKEN }}
